/*********************************************************
 * From C PROGRAMMING: A MODERN APPROACH, Second Edition *
 * By Bill Sun                                           *
 * Copyright (c) 2016, 1998 CaptainAllred Incorperated.  *
 * All rights reserved.                                  *
 * This program may  not be freely distributed,          *
 * provided that this copyright notice is retained.      *
 *********************************************************/
/* NO9.c (Chapter 9, page 153) */
#define _CRT_SECURE_NO_DEPRECATE /*Before all the includes*/
#include <stdio.h> /*scanf printf getchar putchar*/
#include <stdlib.h> /*system abs(int) srand rand*/
#include <stdbool.h> /*bool true false*/
#include <ctype.h> /*toupper tolower isalpha isupper islower*/
#include <math.h> /*sqrt fabs(double) trunc*/
#include <string.h> /*mencpy*/
#include <time.h> /*time*/
#include <iostream> /*C++ input and output*/
using namespace std; /*C++ cout cin*/
/*********************
 * #define Bool int  *
 * typedef int Bool; *
 *********************/
/********************************************************
 *PC-Lint check                                         *
 *C:/Lint/Lint-nt -i"C:/Lint" -u cmd_std.lnt D:/lint.cpp*
 ********************************************************/

void Create_magic_square(int ,unsigned short int [][99]);

void Printf_magic_square(int ,unsigned short int [][99]);

int Input_n(void);

int main(void)
{
	unsigned short int magic_sqaure[99][99];
	int n;
	n=Input_n();
	Create_magic_square(n,magic_sqaure);
	Printf_magic_square(n,magic_sqaure);
	system("pause");
	return 0;
}

int Input_n(void)
{
	bool checkpoint;
	int n;
	unsigned char ch;
	do
	{
		checkpoint=false;n=0;
		printf("Generating a magic sqaure, please input its length n(1<=n<=99):");
		scanf("%d",&n);
		while((ch=getchar())!='\n') continue;
		if (n<=0||n>=100) {printf("Error, unexpected n.\n");checkpoint=true;}
	}while(checkpoint);
	return n;
}

int X_usual_next(int x,int n)
{
	x=x+1;
	if (x>=n) x=0;
	return x;
}

int Y_usual_next(int y,int n)
{
	y=y-1;
	if (y<0) y=n-1;
	return y;
}

int Y_unusual_next(int y,int n)
{
	y=y+1;
	if (y>=n) y=0;
	return y;
}

int Succeed_x(int x,int y,int n,unsigned short int magic[][99])
{
	if(magic[X_usual_next(x,n)][Y_usual_next(y,n)]==0) return X_usual_next(x,n);
	else return x;
}

int Succeed_y(int x,int y,int n,unsigned short int magic[][99])
{
	if(magic[X_usual_next(x,n)][Y_usual_next(y,n)]==0) return Y_usual_next(y,n);
	else return Y_unusual_next(y,n);
}

void Create_magic_square(int n,unsigned short int magic[][99])
{
	int x,y,former_x,former_y;
	
	for(int i=0;i<=n-1;i++)
		for(int ii=0;ii<=n-1;ii++)
			magic[i][ii]=0;
	
	x=n/2+n%2-1;y=0;
	magic[x][y]=1;
	
	for(int i=2;i<=n*n;i++)
	{
		former_x=x;former_y=y;
		x=Succeed_x(former_x,former_y,n,magic);
		y=Succeed_y(former_x,former_y,n,magic);
		magic[x][y]=i;
	}
}

int Longest_length(int n)
{
	int end=n*n,each_length=0;
	while(end>0)
	{
		end=end/10;
		each_length=each_length+1;
	}
	return each_length;
}

int Its_length(int each)
{
	int length=0;
	while(each>0)
	{
		length=length+1;
		each=each/10;
	}
	return length;
}

void Print_line(int n)
{
	int line_length;

	line_length=Longest_length(n)*n+n-1;
	for (int i=1;i<=line_length;i++)
		printf("=");
	printf("\n");
}

void Printf_magic_square(int n,unsigned short int magic[][99])
{
	int each_space=Longest_length(n),now_space;
	printf("Magic square (%dx%d) generated by Bill.\n",n,n);
	
	Print_line(n);
	for (int i=0;i<=n-1;i++)
	{
		for(int ii=0;ii<=n-1;ii++)
		{
			now_space=each_space-Its_length(magic[ii][i]);
			for(int space=1;space<=now_space;space++) printf(" ");
			
			printf("%hu ",magic[ii][i]);
		}
		printf("\n");
	}
	Print_line(n);
}
